[package]
name = "drinklogger"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pwr-hd44780  = "0.1.3"
# mfrc522 = "0.2"
rfid-rs = "0.1"
spidev = "0.4"
# linux-embedded-hal = "0.2"
rand = "0.8"